apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-application
spec:
  selector:
    matchLabels:
      app: welcome-application
  replicas: 3
  template:
    metadata:
      labels:
        app: welcome-application
    spec:
      containers:
        - name: welcome-application
          image: "codingmonks/welcome-application:v1" # match with image in skaffold.xml
          ports:
            - containerPort: 8090